name: Simple CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo Hello
        run: echo "Hello, World!"

      - name: Echo Current Branch
        run: echo "Current branch: ${{ github.ref }}"
