name: CI/CD Pipeline

on:
  workflow_dispatch:  # Allows you to trigger the workflow manually
  push:
    branches:
      - main  # Trigger pipeline on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Clear pip cache
      run: |
        pip cache purge

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Lint Code
      run: echo "Project Linting"
      

    - name: Run Unit Tests
      run: |
        python -m unittest discover

    - name: Build Docker Image
      run: echo "Building Docker image"

    - name: Deploy to Development
      run: echo "Deploying to development environment"

    - name: Deploy to Staging
      if: github.ref == 'refs/heads/main' && success()  # Only deploy to staging if tests pass
      run: echo "Deploying to staging environment"

    - name: Deploy to Production
      if: github.ref == 'refs/heads/main' && success()  # Only deploy to production if staging is successful
      run: echo "Deploying to production environment"
