name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature-model-training
      - feature-api
      - feature-frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Clear pip cache
      run: |
        pip cache purge

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train model
      run: |
        python main.py
        sleep 5  # Wait for the model to create
        
    - name: Run Flask Server
      run: |
        python app.py & 
        sleep 5  # Wait for the server to start
      
    - name: Run Unit Tests
      run: |
        echo "Running Unit Tests"
        python test.py
        
    - name: Format Code
      run: |
        black app.py main.py test.py

    - name: Run flake8
      run: |
        flake8 app.py main.py test.py

    - name: Build Docker Image
      run: |
        docker build -t house-price-predictor .

    - name: Push Docker Image echo
      run: |
        echo "Image push to docker sucessfully"

    - name: Push Docker Image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag house-price-predictor ${{ secrets.DOCKER_USERNAME }}/house-price-predictor:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/house-price-predictor:latest

    - name: Deploy to Development
      run: |
        echo "Deploying to development environment"

    - name: Deploy to Staging
      if: github.ref == 'refs/heads/main' && success()
      run: |
        echo "Deploying to staging environment"

    - name: Deploy to Production
      if: github.ref == 'refs/heads/main' && success()
      run: |
        echo "Deploying to production environment  VERCEL"
        vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
